# Generated by Django 5.0.7 on 2024-07-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accesstokenzoho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='accesstokenzoho',
            name='scope',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='scope'),
        ),
    ]
