# Generated by Django 5.0.7 on 2024-07-12 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_accesstokenzoho_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='organization id'),
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
