# Generated by Django 5.0.7 on 2024-07-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_organization_id_organization_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='OrganizationZoho',
        ),
    ]
